### ISSUE TITLE
Import recipients stuck on 5%

### ISSUE THREAD

**Issue by johnny-longneck** [mindtwo/magento2-cleverreach#1]
Hello,

I installed the module in our test environment. Tested it and the import worked.
Then I removed the Magento receipients.
Installed the module on the production environment and tried to import the correct receipients. It got stuck on 5% always.

Any clue?

**Comment by jonasemde** [comment]
We are not the module maintainer. This repository is only a fork of: https://marketplace.magento.com/clever-magento2.html

Please contact the package maintainer for any further questions.
