### ISSUE TITLE
Wrong group for guest subscribers

### ISSUE THREAD

**Issue by aberti** [mindtwo/magento2-cleverreach#2]
When guest is subscribing to our newsletter (without making order or registering) email is assigned to "General" group regardless of the mapping.

quickfix for that could be:

vendor/mindtwo/magento2-cleverreach/Observer/CustomerSubscribeObserver.php:135
```
if($customer->isEmpty()){
   $customer->setGroupId(0);
}  
```

**Comment by jonasemde** [comment]
We are not the module maintainer. This repository is only a fork of: https://marketplace.magento.com/clever-magento2.html

Please contact the package maintainer for any further questions.
