### ISSUE TITLE
Exception #0 (InvalidArgumentException)

### ISSUE THREAD

**Issue by dmconnector** [mindtwo/magento2-cleverreach#3]
Hi,
after Installtion there is CleverReach Button in Magento Backend,
but I got an error:
Exception #0 (InvalidArgumentException): CleverReach\CleverReachIntegration\IntegrationCore\Infrastructure\Interfaces\Required\Configuration is not defined.

**Comment by jonasemde** [comment]
We are not the module maintainer. This repository is only a fork of: https://marketplace.magento.com/clever-magento2.html

Please contact the package maintainer for any further questions.
